const mongoose = require("mongoose");

// ── AiAnalysis ──────────────────────────────────────────────────────────────
// Stores AI-generated analysis for an attempt.
// type = "performance" → generated after exam submission (strengths, weaknesses, study tips)
// type = "cheat"       → generated by instructor on demand from cheat logs
const aiAnalysisSchema = new mongoose.Schema(
  {
    attempt: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Attempt",
      required: true,
    },
    student: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    exam: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Exam",
      required: true,
    },

    // Discriminates between different analysis types
    type: {
      type: String,
      enum: ["performance", "cheat"],
      required: true,
    },

    // ── Performance analysis fields ───────────────────────────────────────
    // Overall summary paragraph
    summary: { type: String, default: "" },
    // Top strong areas identified
    strengths: { type: [String], default: [] },
    // Areas that need improvement
    weaknesses: { type: [String], default: [] },
    // Recommended topics/resources to study
    recommendations: { type: [String], default: [] },
    // Predicted readiness for re-attempt (0-100)
    readinessScore: { type: Number, default: 0 },

    // ── Cheat analysis fields ─────────────────────────────────────────────
    // 0 = no risk, 100 = definite cheating
    riskScore: { type: Number, default: 0 },
    // Human-readable explanation for the instructor
    explanation: { type: String, default: "" },
    // Specific evidence bullets (e.g., "Tab switched 5 times in 3 minutes")
    evidence: { type: [String], default: [] },
    // Recommendation for the instructor (e.g., "Review attempt", "Flag for review")
    recommendation: { type: String, default: "" },

    generatedAt: { type: Date, default: Date.now },
  },
  { timestamps: true }
);

// Compound index so we can quickly look up analysis by attempt + type
aiAnalysisSchema.index({ attempt: 1, type: 1 }, { unique: true });

module.exports = mongoose.model("AiAnalysis", aiAnalysisSchema);
