const mongoose = require("mongoose");

// ── Test Case sub-schema (for coding questions) ────────────────────────────
const testCaseSchema = new mongoose.Schema(
  {
    input: { type: String, default: "" },
    expectedOutput: { type: String, required: true },
    // Hidden test cases are not shown to the student before/during the exam.
    // They are only revealed on the result page.
    isHidden: { type: Boolean, default: false },
    // Weight: contribution of this test case to the total question score.
    // All weights should sum to 1.0 across a question's test cases.
    weight: { type: Number, default: 1 },
    label: { type: String, default: "" }, // e.g. "Edge case: empty input"
  },
  { _id: false }
);

const questionSchema = new mongoose.Schema(
  {
    text: {
      type: String,
      required: [true, "Question text is required"],
    },

    // ── Question type ────────────────────────────────────────────────────────
    // mcq       → multiple choice (existing)
    // truefalse → true or false (existing)
    // written   → open-ended text, graded by Ollama AI
    // coding    → code submission, executed by Gemini AI
    type: {
      type: String,
      enum: ["mcq", "truefalse", "written", "coding"],
      required: true,
    },

    // ── MCQ fields ────────────────────────────────────────────────────────────
    // 4 strings for MCQ; empty array for True/False/Written/Coding
    options: [String],

    // Stores the exact text of the correct answer.
    // For MCQ/TF: exact string match. For written/coding: leave empty.
    correctAnswer: { type: String, default: "" },

    // Shown to the student on the result review page after submission
    explanation: { type: String, default: "" },

    // ── Written question fields ───────────────────────────────────────────────
    // The instructor's ideal answer — used by Ollama to grade the student's answer.
    modelAnswer: { type: String, default: "" },
    // Plain-English rubric: what makes a good answer (passed to Ollama as context).
    gradingCriteria: { type: String, default: "" },

    // ── Coding question fields ────────────────────────────────────────────────
    // Starter/template code shown in the editor when the student opens the question.
    codeTemplate: { type: String, default: "" },
    // Languages allowed for this question.
    // Supported: "python", "javascript", "cpp"
    allowedLanguages: {
      type: [String],
      default: ["python", "javascript", "cpp"],
    },
    // Execution time limit in seconds (default 5s)
    timeLimit: { type: Number, default: 5 },
    // Execution memory limit in MB (default 128 MB)
    memoryLimit: { type: Number, default: 128 },
    // Test cases: public (shown to student) + hidden (only on results)
    testCases: [testCaseSchema],

    // ── Common scoring ────────────────────────────────────────────────────────
    // For MCQ/TF this is typically 1 (or whatever the exam totalScore distributes).
    // For written/coding this is the max points AI can award.
    maxScore: { type: Number, default: 10 },

    // ── Metadata ──────────────────────────────────────────────────────────────
    category: { type: String, default: "" },
    tags: [String],
    difficulty: {
      type: String,
      enum: ["easy", "medium", "hard"],
      default: "medium",
    },

    // instructor is always set from req.user._id — never from req.body
    instructor: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    // Flag set to true when this question was auto-generated by AI
    aiGenerated: { type: Boolean, default: false },

    // Soft-delete flag so past attempts can still see deleted questions
    isDeleted: { type: Boolean, default: false },
  },
  { timestamps: true }
);

// ── Validation ────────────────────────────────────────────────────────────────
questionSchema.pre("validate", function (next) {
  if (this.type === "mcq") {
    if (!this.options || this.options.length < 2) {
      return next(new Error("MCQ questions must have at least 2 options."));
    }
    if (!this.options.includes(this.correctAnswer)) {
      return next(
        new Error("correctAnswer must be one of the provided options.")
      );
    }
  }

  if (
    this.type === "truefalse" &&
    !["True", "False"].includes(this.correctAnswer)
  ) {
    return next(
      new Error(
        "correctAnswer must be 'True' or 'False' for true/false questions."
      )
    );
  }

  if (this.type === "written" && !this.modelAnswer) {
    return next(
      new Error("Written questions require a modelAnswer for AI grading.")
    );
  }

  if (this.type === "coding" && (!this.testCases || this.testCases.length === 0)) {
    return next(
      new Error("Coding questions require at least one test case.")
    );
  }

  next();
});

module.exports = mongoose.model("Question", questionSchema);
